name: Test and static analysis
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Composer dependencies
        run: composer install
      - name: PHPUnit
        run: composer test
      - name: PHPStan
        run: composer stan
      - name: PHP-CS-Fixer
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: php-cs-fixer check --diff
